name: Generate PHPDoc

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  generate-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate PHP Documentation
        run: |
          docker run --rm -v ${{ github.workspace }}:/data phpdoc/phpdoc:3 -d src -t docs/api

      - name: Upload Documentation Artifact
        uses: actions/upload-artifact@v3
        with:
          name: phpdoc
          path: docs/api
